### ISSUE TITLE
I would love more Wikidata lookup options

### ISSUE THREAD

**Issue by susannaanas** [tomayac/wikipedia-tools-for-google-spreadsheets#12]
Would it be possible to have Wikidata lookups based on Qid's? It would be handy if the disambiguation has already been dealt with. Perhaps also looking up a specific property, rather than all of them. After reading more I see this is practically the same as issue #10

**Comment by tomayac** [comment]
@susannaanas I have just released a new version of the addon that allows you to specify a Wikidata qid for `WIKIDATAFACTS` lookups like so: `WIKIDATAFACTS("Q42")`. I am now working on adding a third parameter to the function that would allow you to limit the results to a subset of properties. I'll update the issue once this is released as well.

**Comment by tomayac** [comment]
@susannaanas Alright, this is now fully working. You can as of now say…
`WIKIDATAFACTS("Q42", "all", "P106")`
…to get all of Douglas Adams' occupations (i.e., `P106`). If you replace `"all"` with `"first"`, you will just get the first occupation. If you want several properties, pass them as an array like…
`WIKIDATAFACTS("Q42", "all", {"P31"; "P106"})`

**Comment by tomayac** [comment]
See the new functionalities [in action](https://docs.google.com/spreadsheets/d/1QuUVFl6x3c1Yj3J7jd_OTHYD2haVFVtebIw2It4KNoA/edit?usp=sharing).

**Comment by fokky** [comment]
Awesome! Thank you 💃

**Comment by susannaanas** [comment]
Hi Thomas!

It has taken me all these days to get down to try it out... Im really
excited about this! Big thanks!!

Cheers
Susanna

2016-10-29 15:21 GMT+03:00 Thomas Steiner <notifications@github.com>:

**Comment by tomayac** [comment]
I have just added a new function called ```WIKIDATADESCRIPTIONS``` ([live demo](https://docs.google.com/spreadsheets/d/1xtj6H6H_4WcktqIpKpITGBeDE8jZQHyeEhgrv4PSfkQ/edit?usp=sharing)) that, as the name suggests, pulls in descriptions from Wikidata. For consistency reasons, I have further renamed the function ```WIKIDATALABEL``` (singular) to ```WIKIDATALABELS``` (plural). I thought this might be of interest for @susannaanas @fokky @Nautic.
