### ISSUE TITLE
Remove the 2000 unused rows from the spreadsheet

### ISSUE THREAD

**Issue by quiddity-wp** [tomayac/wikipedia-tools-for-google-spreadsheets#16]
The intriguing looking spreadsheet demo, has about 2,000 unneeded rows, and a couple dozen unneeded columns. I suggest removing those, to make the whole thing load faster.

Also it isn't currently working for most of the columns - screenshot: http://imagizer.imageshack.com/img923/5853/MAtyDS.png - possibly related?
https://docs.google.com/spreadsheets/d/1sVduZul787O-bRzuy0UKpRl7bkouxwaIOsxXuJGm6yg/edit#gid=0

**Comment by tomayac** [comment]
Done, cropped the sheet to the actual data (with some headspace), thanks for the suggestion, @quiddity-wp. When the sheet is empty, the Google Sheets [https://developers.google.com/apps-script/guides/services/quotas#current_quotas](quota) has been reached. There is discussion in https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/issues/21 going on to make this not a silent failure. Closing this issue.

**Comment by quiddity-wp** [comment]
Awesome, thank you x2!
