### ISSUE TITLE
WIKITRANSLATE - Option to populate only one language output

### ISSUE THREAD

**Issue by srikanthlogic** [tomayac/wikipedia-tools-for-google-spreadsheets#18]
When I use WIKITRANSLATE("en:Anna Salai","ta",false) as a formula, I would expect only the ta translation of the English wiki article to populated in the cell and not an array as response. This could help in translating a list of articles by having corresponding column the translated value, which isnt possible now.

**Comment by tomayac** [comment]
You can get the desired behavior by using the [INDEX](https://support.google.com/docs/answer/3098242?hl=en) function.
