### ISSUE TITLE
Feature request: Wikidata Q number for a given Wikipedia article

### ISSUE THREAD

**Issue by fokky** [tomayac/wikipedia-tools-for-google-spreadsheets#2]
Hi! Thanks for this very useful tool. Here's a feature request: I'd find it extremely helpful to be able to return simply the Wikidata Q number for a given Wikipedia article. E.g. en:Digital art would be Q860372. Thanks!

**Comment by tomayac** [comment]
Done :-)

**Comment by fokky** [comment]
Sweet. Thank you!
