### ISSUE TITLE
Help with use of WIKIDATAFACTS

### ISSUE THREAD

**Issue by alexrollin** [tomayac/wikipedia-tools-for-google-spreadsheets#22]
Hello! with the WIKIDATAFACTS function, is it possible to grab the taxon common name in Indonesian, shown underlined here in red?

Help with the syntax would be very welcome for both :
 - opt_multiObj | string= | Whether to return all object values (pass all) or just the first (pass first) when there are more than one object values (optional).
- opt_properties | Array<string> opt_properties Limit the resulting facts to a list of properties (optional).

![image](https://user-images.githubusercontent.com/114659/29678447-32bdb296-8931-11e7-8471-dbf842290b84.png)

I don't understand the instructions, and there isn't an example in the docs that uses the string= argument.

![image](https://user-images.githubusercontent.com/114659/29678544-917385b8-8931-11e7-96c2-7ad942903847.png)

**Comment by viswam** [comment]
It is indeed  possible.
=WIKIDATAFACTS(P3,"first","P1843")
where P3 is id:Cipoh_kacat

However, the help documentation for certain functions such as this, is too short.
It will be great if the documentation can be in more detail and descriptive. :)

**Comment by tomayac** [comment]
Thanks for helping out, @viswam. I have a backlog of open issues that I want to address at some point, so any help with improving the docs is welcome. Here is the [to-be-expanded example section](https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/blob/2b6dced57aba753c8a173c806de82ecdf3999a0a/Documentation.html#L602-L607). You need to check the file locally to make sure the indentation with the ```<pre>``` works fine. I'm closing this very Issue.
