### ISSUE TITLE
WIKIDATAFACTS display options

### ISSUE THREAD

**Issue by davidmw** [tomayac/wikipedia-tools-for-google-spreadsheets#23]
I'm finding wikidatafacts rather awkward to integrate into an existing spreadsheet. I have one search topic per row and wikidatafacts returns a one or two dimensional array that expands into neighboring cells.

It would be very useful to turn off the property name so a simple query for something like 'birth name' would be limited to a single cell.  When multiple items are returned maybe it could be as a JSON string?

David

**Comment by davidmw** [comment]
Sorry - I can probably do this directly on the spreadsheet. Will close with examples asap.

**Comment by tomayac** [comment]
You can use the native ```INDEX``` ([documentation](https://support.google.com/docs/answer/3098242)) function as well.

**Comment by davidmw** [comment]
Yes INDEX works fine but I've not yet been able to eliminate the first column of a 2d array that is returned. I'll probably JOIN the results but would like to eliminate all the property names. 



On 4 Sep 2017, at 5:47 pm, Thomas Steiner <notifications@github.com> wrote:

You can use the native INDEX (documentation) function as well.

**Comment by tomayac** [comment]
One way of doing it is the ```QUERY``` function:

```QUERY(WIKIDATAFACTS(…), "SELECT Col2")```

Not sure if it’s the best way, though, but this allows you to, well, query your data, which is quite powerful.

**Comment by davidmw** [comment]
Many thanks. Putting this to work on many cells resulted in Error returns due to the high rate of calls. I've moved all WIKIDATAFACTS calls to a script which is quite slow (updating cells instead of ranges) and solves the rate and lockout problem.

I've now stumbled onto the lock service https://developers.google.com/apps-script/reference/lock/ and wonder if this would be useful in your functions to eliminate concurrent execution.

**Comment by alexrollin** [comment]
I also find this awkward, and will be making a second sheet where the results show up in the format I need them.

**Comment by tomayac** [comment]
Closing remark: the [rate limit](https://developers.google.com/apps-script/guides/services/quotas#current_quotas) in Google Sheets for external requests is seriously limiting, and also still some users get hit by the "stuck in 'loading' state" [issue](https://issuetracker.google.com/issues/36759198). Outsourcing to other sheets might help indeed.
