### ISSUE TITLE
Rate limit ?

### ISSUE THREAD

**Issue by alexrollin** [tomayac/wikipedia-tools-for-google-spreadsheets#24]
The script is having some kind of problem. Should I wait until my rate limit is reset?

I don't know what the problem is, but, it could definitely be too many rows. 150? With 6 queries per row?

![image](https://user-images.githubusercontent.com/114659/30175255-75456906-9430-11e7-8f6f-2ed39f07c8be.png)

![image](https://user-images.githubusercontent.com/114659/30175331-ba045d2c-9430-11e7-8f04-220704dd27a8.png)

**Comment by tomayac** [comment]
This looks like a rate limit issue (of Google Sheets) indeed. It is tracked in https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/issues/21.
