### ISSUE TITLE
Our update on how we use this now and what we are thinking

### ISSUE THREAD

**Issue by alexrollin** [tomayac/wikipedia-tools-for-google-spreadsheets#25]
Hello,

We have been working with this in a google sheet for a couple months now.

We can come up with a little description of how we use it and what we would like to do next.

Mainly:

1. A feature to query directly from the QID for labels
2. Formatting Output for wikidata to cells on the right , not flowing down
3. Have some way of "not" updating cells so we don't hit the rate limit
4. Start to think about how to push information to wikidata (oos, fair enough)

https://docs.google.com/document/d/1jUziaQjMV4BLHL8scluooASsZMiJxv3z156L2c1DXLY/edit

Feedback is greatly appreciated!

**Comment by tomayac** [comment]
Hi @alexrollin. Sorry for the long turn-around time. Let me address your points:
- A feature to query directly from the QID for labels
👉 I think this is covered in https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/issues/17.
- Formatting Output for wikidata to cells on the right , not flowing down
👉 You can do this with the [TRANSPOSE](https://support.google.com/docs/answer/3094262?hl=en) function. 
- Have some way of "not" updating cells so we don't hit the rate limit
👉 This is being looked at in https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/issues/21.
- Start to think about how to push information to wikidata (oos, fair enough)
👉 Out-of-scope indeed.

Thanks for the description in your [document](https://docs.google.com/document/d/1jUziaQjMV4BLHL8scluooASsZMiJxv3z156L2c1DXLY/ed), this sounds like a good use case for this add-on. 

I'm closing this issue in favor of the referenced issues above. Please chime in there. Thanks!
