### ISSUE TITLE
WIKIDATA

### ISSUE THREAD

**Issue by Elenafrost** [tomayac/wikipedia-tools-for-google-spreadsheets#29]
Hi there, 

Thank you for this wonderful tool! 
I'm looking to return 1 property with WIKIDATAFACTS so I used the following formula : 

=WIKIDATAFACTS(A2;"first";P586) 

I'm still getting all of the information instead of just one character, am I doing something wrong?
(FYI I'm using a French version of sheets so the commas take the form of a semicolon)

Thank you for your help!

Elena 

![screen shot 2018-10-04 at 14 12 35](https://user-images.githubusercontent.com/43845011/46473207-a4b8a980-c7df-11e8-8706-74559d027d42.png)

**Comment by tomayac** [comment]
Ah, if you want to limit to just property P586, pass it as a string: `WIKIDATAFACTS(A2; "first"; "P586")`.
