### ISSUE TITLE
WIKIDATAFACTS's opt_properties hard to understand

### ISSUE THREAD

**Issue by chuaweijie** [tomayac/wikipedia-tools-for-google-spreadsheets#35]
WIKIDATAFACTS's opt_properties is hard to understand. I would suggest adding a link to the [Wikipedia's properties](https://www.wikidata.org/wiki/Wikidata:Database_reports/List_of_properties/all). That would help a lot of users.

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/pull/36. Thanks!

**Comment by MichelWiki** [comment]
Hello
Sorry , I still don"t understand how to use "opt_properties " option in wikidatafacts. I would suggest adding just an exemple in your documentation
For instance I want to extract "date of birth" . It is "P589" property .

**Comment by tomayac** [comment]
@MichelWiki Sorry for the delay, I was out of office. This is how you'd just get the date of birth:

```=WIKIDATAFACTS("en:Barack_Obama", "all", "P569")```

Screenshot from this [sheet](https://docs.google.com/spreadsheets/d/1x1T3sDHv3Yf1OsNBArjJzcBZA0o6Sf-hjLE_-FZpi6g/edit?usp=sharing):

<img width="344" alt="Screen Shot 2020-03-12 at 16 18 54" src="https://user-images.githubusercontent.com/145676/76536877-3ae50a80-647d-11ea-9231-15289c88f360.png">

**Comment by MichelWiki** [comment]
Thanks a lot ! You proved tha example is better than a long explanation
