### ISSUE TITLE
Error: Function not rcognised

### ISSUE THREAD

**Issue by Llywelyn2000** [tomayac/wikipedia-tools-for-google-spreadsheets#38]
The tool worked perfectly until around 17.00 yesterday, and has been down since.

**Comment by tomayac** [comment]
Most probably you have exceeded your daily quota for URL Fetch calls that the plugin uses internally to communicate with the Wikipedia and Wikidata APIs. You can see the quota here: 
https://developers.google.com/apps-script/guides/services/quotas#current_quotas.

**Comment by Llywelyn2000** [comment]
Thnaks! Might be for me, but not for two other users who hadn't used it yesterday. They get the same message.

**Comment by tomayac** [comment]
Can you try the solutions from this answer: https://stackoverflow.com/questions/32077904/custom-function-not-recognized. The Google Sheets backend occasionally gets stuck :-(

**Comment by Llywelyn2000** [comment]
No. Tried 4 diff browsers.
Do they work for you? Try =WIKIDATAQID(CONCAT("en:",B2)) in B1; enter 'London' or 'Madrid' in B2. Should return the Qcode (Qid).

**Comment by tomayac** [comment]
It worked. One tip is to open the documentation, this helps "kick" the loading of the add-on. See the screenshot below for how to do this:

<img width="1616" alt="Screen Shot 2020-04-08 at 09 29 48" src="https://user-images.githubusercontent.com/145676/78756713-8951d000-797b-11ea-9660-347c98cbbf10.png">

**Comment by Llywelyn2000** [comment]
It worked! Reminds me of starting our old Morris Oxford by hand, back in the early 70s! But it worked!
Thanks for your time and patience!

**Comment by tomayac** [comment]
Happy it worked. I also [looked up Morris Oxford](https://www.google.com/search?q=morris+oxford&oq=morris+oxford) and was not disappointed. What a diamond!
