### ISSUE TITLE
WIKIOUTBOUNDLINKS dosen't shows the link, only the name of the link

### ISSUE THREAD

**Issue by GGilada** [tomayac/wikipedia-tools-for-google-spreadsheets#39]
after using WIKIOUTBOUNDLINKS function, I get an Array of the name of the links, but it's just a text and not a link

**Comment by tomayac** [comment]
That's expected. To convert the *"name of the links"* into a clickable hyperlink, you need another formula: `=HYPERLINK("https://"&$A$1&".wikipedia.org/wiki/"&B1)` (where `$A$1` is a reference to a cell with the language like `"en"`, and `B1` a reference to a cell with a *"name of the links"*).
