### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by chsteiner** [tomayac/wikipedia-tools-for-google-spreadsheets#44]
The entire tool seems broken. See your example spreadsheet: https://docs.google.com/spreadsheets/d/1sVduZul787O-bRzuy0UKpRl7bkouxwaIOsxXuJGm6yg

**Comment by tomayac** [comment]
Google Sheets sometimes gets stuck. I have just re-triggered all the formulas and the sheet has data again. It's very unfortunate, but sometimes just adding a space to a formula so it gets parsed anew is the only fix.
