### ISSUE TITLE
Coordinates not included in WIKIDATAFACTS

### ISSUE THREAD

**Issue by chsteiner** [tomayac/wikipedia-tools-for-google-spreadsheets#45]
Do you have any idea why the property https://www.wikidata.org/wiki/Property:P625 is not included in the output of WIKIDATAFACTS? When explicitly targeted via opt_properties the field is left blank. When not targeted it is omitted in the list of properties/facts. Example: =WIKIDATAFACTS("Q1017") or =WIKIDATAFACTS("Q1017";all;"P625")

**Comment by chsteiner** [comment]
Here it is: ![image](https://user-images.githubusercontent.com/28706050/155946487-3a55d188-8966-4e1f-b6f8-2f2c0b664f02.png)

The case for geocoordinates is missing. Looks like this in the API:
![image](https://user-images.githubusercontent.com/28706050/155946611-70c88c94-20b0-4d0f-8db6-3ca8b9bd1c9a.png)

Could you add that case?

**Comment by tomayac** [comment]
This is a nested datatype:

```json
{
  "snaktype": "value",
  "property": "P625",
  "hash": "c1830e2ab31e9b6426f104d3ee9cf5eea757dec3",
  "datavalue": {
    "value": {
      "latitude": 50.776207,
      "longitude": 6.083788,
      "altitude": null,
      "precision": 0.000277778,
      "globe": "http://www.wikidata.org/entity/Q2"
    },
    "type": "globecoordinate"
  },
  "datatype": "globe-coordinate"
}
```

The fastest would be if you copy the existing `WIKIDATA()` function, make the changes you need to extract this nested datatype according to your requirements, and save it as your personal [custom function](https://developers.google.com/apps-script/guides/sheets/functions) that you can name something like `MYWIKIDATA()`.
