### ISSUE TITLE
Wikitranslate help documentation needs revision

### ISSUE THREAD

**Issue by arjunaraoc** [tomayac/wikipedia-tools-for-google-spreadsheets#47]
Current documentation is like
=WIKITRANSLATE(
  "en:Berlin"
  {"ab"; "ace"; "af"}
)

It should be changed to
=WIKITRANSLATE(
  "en:Berlin",
   xxxx
)

where XXX  is "te" for one language
and is not known to me for  more than one language

**Comment by tomayac** [comment]
It's just meant as an example to illustrate it takes a list of languages. You can of course only pass `{"te"}` and nothing else.
