### ISSUE TITLE
How to get last value while using WIKIDATAFACTS() function?

### ISSUE THREAD

**Issue by AramBakir** [tomayac/wikipedia-tools-for-google-spreadsheets#49]
Hello, I want to know how to get last value using WIKIDATAFACTS() function? For example, `=WIKIDATAFACTS("Q86733728","all",{"P1120"})` returns too many values, but i just want to get the last one which is the current or latest result. Actually, I think there should be "last" value for the second parameter because there are both "first" and "all" values. Thank you in advance!

**Comment by tomayac** [comment]
You can just [use regular Google Sheets functions m](https://spreadsheetpoint.com/get-last-value-in-column-google-sheets/) to achieve this.
