### ISSUE TITLE
Create sum for WikiPageViews

### ISSUE THREAD

**Issue by Sadads** [tomayac/wikipedia-tools-for-google-spreadsheets#5]
Hey Tomayac, one more request. So the current WikiPageViews function returns an array of results for each individual day within a range of dates, but there are a number of situations where program leaders and folks will want to do sums of groups of days. Is there a possibility to add a boolean, or variable option at the end of WikiPageviews, which allows different outputs-- one of them being a sum of the pageviews, and one being an array? I could think of others as well (mean daily, for example).

**Comment by tomayac** [comment]
This can be done natively, as in this [example](https://docs.google.com/spreadsheets/d/1V6QAmUghrShHZI9HO_Cj7w-68H8VLP3iatZ_MS2WYmc/edit?usp=sharing):
```=SUM(QUERY(WIKIPAGEVIEWS("en:Wikipedia"), "SELECT Col2"))```

**Comment by Sadads** [comment]
Yeah, we figured something like that out for ourselves. However, doing
sophisticated parsing of arrays within formulas, is a bit beyond the
skill/knowledge of some of your reusers (I wonder if that can be either
integrated into the documentation, if you don't want to build it in as a
function).

Cheers,

Alex

**Comment by tomayac** [comment]
Fair enough, I agree that this convenience feature could be supported. I reopen the Issue and will implement it as soon as I have some spare cycles.

**Comment by Sadads** [comment]
Thanks your awesome!

Cheers,

Alex

**Comment by tomayac** [comment]
@Sadads, this has finally been closed with https://github.com/tomayac/wikipedia-tools-for-google-spreadsheets/commit/a20bed77d4d282bdf8ca85c140b0b5dd82febe9d. The new version has just been deployed.
