### ISSUE TITLE
WIKISEARCH argument for # of results returned

### ISSUE THREAD

**Issue by NathanR-85** [tomayac/wikipedia-tools-for-google-spreadsheets#53]
Lots of potential here... but I only want WIKISEARCH to return 1 result, so I can have many searches going on a single sheet (one per row) and only receive the top result. 

Currently, if I try to duplicate the formula in each row, I get **#REF Error: Array result was not expanded because it would overwrite data in C3**. The search is broken by any data in the cells below it. Ignoring this error and writing the cells anyway would be an easier fix in theory, but I'm not sure if that's possible.

Is that possible?

Thanks!

**Comment by NathanR-85** [comment]
Also, it would be helpful to have the URL of the search result appear in the next column, so we can visit the page.

**Comment by NathanR-85** [comment]
Nevermind, I was able to do this with Google App Script, then I'll use your app for the rest of the functionality.

**Comment by tomayac** [comment]
Thanks for letting me know. You can also use the [`INDEX()`](https://support.google.com/docs/answer/3098242?hl=en) function directly in Sheets.
