### ISSUE TITLE
Include Non-Wikipeda APIs

### ISSUE THREAD

**Issue by Sadads** [tomayac/wikipedia-tools-for-google-spreadsheets#6]
Hey Tomayac -- we are beginning to use this fairly extensively for the Wikipedia Library (developing a fairly robust spreadsheet at https://docs.google.com/spreadsheets/d/1hUbMHmjoewO36kkE_LlTsj2JQL9018vEHTeAP7sR5ik/edit#gid=812059281 ) . 

One functionality that might be missing, is calling on the APIs of the other Wikimedia wikis -- I know that a number of tools call on the other projects in a similar fashion as the Wikipedia,s because the APIs are largely structured the same (for example, https://tools.wmflabs.org/pageviews/#project=meta.wikimedia.org&platform=all-access&agent=user&range=latest-20&pages=The_Wikipedia_Library ). It would be great to minimally support meta, the wikisources, and the wiktionaries.

**Comment by tomayac** [comment]
Yes, it seems to be perfectly possible, pending some more investigation. I am currently working on other things, but acknowledge the feature request and will eventually get back to it once time permits :-D

**Comment by Sadads** [comment]
Sounds good :) We're just going to keep pushing for this to be slightly more robust. Its great, and we love it!

**Comment by tomayac** [comment]
@Sadads Sorry for the slow turn-around time :-/ Would you be able to hand-craft example URLs for API calls for me to look at? Thanks!

**Comment by Samwalton9** [comment]
I believe this is the kind of request we'd be looking for on, for example, meta wiki - https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/meta.wikimedia/all-access/all-agents/The_Wikipedia_Library/daily/2015100100/2015103100

**Comment by tomayac** [comment]
@Sadads @Samwalton9 Alright, this has been deployed and is working :-) Please welcome four shiny, new, amazing functions:

```
WIKIPAGEVIEWSPERARTICLE()
WIKIPAGEVIEWSAGGREGATE()
WIKIPAGEVIEWSTOP()
WIKIUNIQUEDEVICES()
```

The functions are undocumented (*in the sidebar*) as they are clearly for **advanced users**, but if you type them in the formula editor, the autocomplete comes up with contextual help, as usual:
 
<img width="389" alt="screen shot 2016-07-31 at 22 23 31" src="https://cloud.githubusercontent.com/assets/145676/17279122/758134be-576d-11e6-93c5-ee42ddb708ec.png">

Here is a quick [demo spreadsheet](https://docs.google.com/spreadsheets/d/14mDUc73AlLjPobt0p-ugI9s8O-nm7W1-JtTW7IFKR4A/edit?usp=sharing) that I have thrown together that also demonstrates their usage.

**Comment by Samwalton9** [comment]
Awesome! Thank you!

**Comment by Sadads** [comment]
This is amazing! Thank you :)

Cheers,

Alex
