### ISSUE TITLE
Support for querying link numbers

### ISSUE THREAD

**Issue by Samwalton9** [tomayac/wikipedia-tools-for-google-spreadsheets#7]
To echo Alex's previous issue; this tool is becoming really useful for the Wikipedia Library, so I have a request for a query that would benefit our partner link tracking. We currently use Special:LinkSearch to ascertain how many links exist to a particular partners' website; it would be great if we could pull the data automatically through this add-on.

Would it be possible to add functionality for querying something like the API's exturlusage through the add-on to get a total number of links? Thanks in advance!

**Comment by tomayac** [comment]
Yes, it seems to be perfectly possible, pending some more investigation. I am currently working on other things, but acknowledge the feature request and will eventually get back to it once time permits :-D

**Comment by tomayac** [comment]
@Samwalton9 Sorry for the slow turn-around time :-/ Would you be able to hand-craft an example URL for an API call for me to look at? Thanks!

**Comment by Samwalton9** [comment]
We would basically like to be able to return the total number of links returned by exturlusage for a given URL. Example API query: https://en.wikipedia.org/wiki/Special:ApiSandbox#action=query&format=json&list=exturlusage&euquery=slashdot.org

**Comment by tomayac** [comment]
@Samwalton9 This has just gone live. Thanks for opening this Issue, this is a super powerful feature of the API that I was not even aware about :-) Glad we have it in Wikipedia Tools now!
