### ISSUE TITLE
Feature request: Labels for Wikidata items

### ISSUE THREAD

**Issue by athalhammer** [tomayac/wikipedia-tools-for-google-spreadsheets#9]
Hi @tomayac,

I really like the toolkit!

It would be cool to have a function that fetches labels for QIDs. Do you think that is feasible? What would be the best way to implement this?

Andreas

**Comment by tomayac** [comment]
@athalhammer A ```WIKIDATALABEL``` function has just been implemented:

<img width="779" alt="screen shot 2016-08-30 at 22 06 40" src="https://cloud.githubusercontent.com/assets/145676/18105036/38cfca3c-6efe-11e6-8c12-43dca97af63f.png">

**Comment by athalhammer** [comment]
Thanks!
